apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      bb: web
  template:
    metadata:
      labels:
        bb: web
    spec:
      containers:
      - name: flask
        image: abhigyan97/flask-app:1.0
---
apiVersion: v1
kind: Service
metadata:
  name: flask-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    bb: web
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30001